spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
tossPayments:
  successUrl: "http://localhost:5173/payment/success"
  failUrl: "http://localhost:5173/payment/fail"
