server:
  port: 8090
spring:
  batch:
    job:
      enabled: false
  profiles:
    active: dev
    include: secret
  jackson:
    serialization:
      fail-on-empty-beans: false
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      auth-code-expiration-millis: 1800000  # 인증코드 만료 시간: 30분
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  file:
    upload-dir: /Users/mingulee/Desktop/uploads/
  web:
    resources:
      static-locations: file:/Users/mingulee/Desktop/uploads/
logging:
  level:
    root: INFO
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: www.goohaeyou.site
    frontUrl: "https://${custom.prod.cookieDomain}"
    backUrl: "https://a.goohaeyou.site"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: goohaeyou
tossPayments:
  clientKey: ${tossPayments.apiClientKey}
  secretKey: ${tossPayments.apiSecretKey}
  url: "https://api.tosspayments.com/v1/payments/"
