server:
  port: 8090
spring:
  profiles:
    active: dev
    include: secret
  jackson:
    serialization:
      fail-on-empty-beans: false
  threads:
    virtual:
      enabled: true
logging:
  level:
    root: INFO
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: goohaeyou.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://a.${custom.prod.cookieDomain}"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: goohaeyou
  temp:
    dirPath: c:\temp
  gen:
    dirPath: c:\temp\goohaeyou\gen
